In [5]:
#creating the array with float values
import numpy as np
x = np.arange(0,3,0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [6]:
#creating 2d array
array_2d = np.array([(1,2,3),(4,5,6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#To get the shape of the array
array_2d.shape

(2, 3)

In [8]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [9]:
#To reshape the array
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
#numirical actions on the arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [11]:
b-a

array([3, 3, 3])

In [12]:
a*b

array([ 4, 10, 18])

In [13]:
b/a

array([4. , 2.5, 2. ])

In [14]:
#to get the reminder
b%a

array([0, 1, 0], dtype=int32)

In [15]:
a < 2

array([ True, False, False])

In [24]:
#modifying an array without creating a new one 
a+=3
a

array([13, 14, 15])

In [26]:
b+=a
b

array([30, 33, 36])

In [28]:
ages = np.array([12,15,18,20])
ages.sum()

65

In [29]:
ages.min()

12

In [30]:
ages.max()

20

In [31]:
# Rows and column operations 
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
#in a given 2d array axis=0 --columns  axis=1 --Rows
numbers.min(axis=0)

array([0, 1, 2, 3])

In [33]:
numbers.max(axis = 1)

array([ 3,  7, 11])

In [35]:
#  Statistical functions
scores = np.array([45,67,89.25,78,21,13,54,74])
print("Mean information scores of the students:")
print(np.mean(scores))


Mean information scores of the students:
55.15625


In [37]:
scores = np.array([45,67,89.25,78,21,13,54,74])
print("Median information scores of the students:")
print(np.median(scores))

Median information scores of the students:
60.5
