In [2]:
import numpy as np
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
#splitting of an array operations
print('split the array in to 3 equal sized subarrays:')
np.split(x,3)

split the array in to 3 equal sized subarrays:


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [4]:
print('split the array at positions indicated in 1-d array:')

np.split(x,[4,7])

split the array at positions indicated in 1-d array:


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [6]:
#Horizontal split
y = np.array([('germany','france','hungary','Austria'),('berlin','paris','budapest','vienna')])

p1,p2 = np.hsplit(y,2)
print(p1)
print(p2)


[['germany' 'france']
 ['berlin' 'paris']]
[['hungary' 'Austria']
 ['budapest' 'vienna']]


In [11]:
#Vertical spli
a,b = np.vsplit(y,2)
print(a)
print(b)

[['germany' 'france' 'hungary' 'Austria']]
[['berlin' 'paris' 'budapest' 'vienna']]


In [13]:
#Iterating
#one dimensional arrays
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [14]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [18]:
#Multi dimensional arrays
import numpy as np
students = np.array([['amith','teja','anil','veena','prasad'],[65,78,90,81,85],[71,82,79,92,95]])

for i in students:
    print('i=',i)

i= ['amith' 'teja' 'anil' 'veena' 'prasad']
i= ['65' '78' '90' '81' '85']
i= ['71' '82' '79' '92' '95']


In [20]:
for element in students.flatten():
    print(element)   #it will print in row wise

amith
teja
anil
veena
prasad
65
78
90
81
85
71
82
79
92
95


In [22]:
#column order--known as Forten order:
for element in students.flatten(order = 'F'):
        print(element)

amith
65
71
teja
78
82
anil
90
79
veena
81
92
prasad
85
95


In [26]:
#nditer
x = np.arange(12).reshape(3,4)
print(x)
for i in np.nditer(x):  #row wise
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
print(x)
for i in np.nditer(x, order = 'F'):   #column wise
      print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
4
8
1
5
9
2
6
10
3
7
11


In [31]:
#Flag concept
print(x)
for i in np.nditer(x,order = 'F',flags = ['external_loop']):
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [39]:
import numpy as np
salaries = np.genfromtxt("C:/Users/anil/Desktop/python/salary.csv",delimiter = ",")
salaries



array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [40]:
salaries.shape

(1147,)

In [41]:
#1. Find out the mean value
mean = np.mean(salaries)
mean

55894.53879686138

In [42]:
#2.Find out the median value
median = np.median(salaries)
median

48000.0

In [43]:
#3.Find out the standard deviation
sd = np.std(salaries)
sd

55170.37550939316

In [44]:
#4.Find out the variance
variance = np.var(salaries)
variance

3043770333.8474483