In [3]:
import numpy as np
array_one = np.array([1,2,3,4])  
array_one

array([1, 2, 3, 4])

In [4]:
#giving tuples in the array
array_2 = np.array([(1,2,3,4),(5,6,7,8)])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
#to get the shape of the array
array_2.shape

(2, 4)

In [6]:
#to get the type of array
type(array_2)

numpy.ndarray

In [8]:
numbers = (1,2,3,4,5,6)
x = np.array(numbers)
x

array([1, 2, 3, 4, 5, 6])

In [13]:
#array of zeros
array_of_zeros = np.zeros((3,4))
array_of_zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#array of ones
array_of_ones = np.ones((4,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#change the data type of the array from float to integer
array_of_ones_int  = np.ones((3,4), dtype=np.int16)
array_of_ones_int


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [17]:
#Empty array
array_empty = np.empty((3,3))
array_empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.82997462e-321],
       [8.90060779e-307, 1.50192485e-307, 4.67296746e-307]])

In [19]:
#identity matrix generation 
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
#to declare a range --arange(start,stop,stepcont,dtype)
# print only even numbers up to 20
array_even = np.arange(2,21,2)
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])